# -*- coding: utf-8 -*-
"""GiamChieu_Housing PCA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WlrvtqfyMCavT3ck9q-aLAh0kOKvr7Zi
"""

from google.colab import drive
drive.mount('/content/drive')

root_path = "drive/My Drive/Colab Notebooks/Source/"

import numpy as np
import pandas as pd

X = pd.read_csv(root_path + 'housing.csv')
X.head()

X.shape

np.mean(X, axis = 0) # tính trung bình của từng thuộc tính np.mean

X_mean = X - np.mean(X, axis = 0)
X_mean[:5]

# Tính hiệp phương sai giữa các cột, tham số rowvar=False cho biết mỗi cột của X_mean biểu thị một biến và các hiệp phương sai sẽ được tính toán giữa các biến.
cov_mat = np.cov(X_mean, rowvar = False)
cov_mat

cov_mat.shape

# Tính giá trị riêng và vector riêng của ma trận hiệp phương sai 
eigen_values, eigen_vectors = np.linalg.eigh(cov_mat)

eigen_values

sorted_index = np.argsort(eigen_values)[::-1]
sorted_eigenvalue = eigen_values[sorted_index] # Sắp xếp giá trị riêng theo giá trị giảm dần
sorted_eigenvectors = eigen_vectors[:,sorted_index] # Sắp xếp vector riêng ứng với giá trị riêng đã sắp xếp

sorted_eigenvalue



n_components = 3
eigenvector_subset = sorted_eigenvectors[:,0:n_components]
# Lấy 3 vector riêng có 3 giá trị riêng lớn nhất

eigenvector_subset

X_reduced = np.dot(eigenvector_subset.transpose(), X_mean.transpose()).transpose()
X_reduced.shape

X_reduced

# Lấy dữ liệu cột đầu tiên
X_reduced[:,0]

# Lấy dữ liệu cột thứ 2
X_reduced[:,1]

# Lấy dữ liệu cột thứ 3
X_reduced[:,2]